config/routes.rb
Rails.application.routes.draw do
  # User Authentication Routes
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Basic Hotel Routes
  resources :hotels do
    resources :reviews, only: [:new, :create]
    resources :room_types, only: [:index, :show]
    resources :bookings, only: [:new, :create, :show]
  end

  # Booking Routes
  resources :bookings, only: [:new, :create, :show, :index]

  # Admin Namespace
  namespace :admin do
    # Admin Dashboard
    get '/', to: 'dashboard#index', as: :dashboard

    # Admin Hotel Management
    resources :hotels, except: [:show] do
      resources :room_types, only: [:new, :create, :edit, :update, :destroy]
    end

    # Admin Booking Management
    resources :bookings, only: [:index, :show, :destroy] do
      member do
        patch 'cancel'
      end
    end

    # Admin User Management
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  # Define root route
  root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hotel
  belongs_to :room_type

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validate :check_dates

  enum status: { pending: 0, confirmed: 1, cancelled: 2 }
  
  private
  def set_default_status
    self.status ||= :pending
  end
  
  def check_dates
      if check_in_date.present? && check_out_date.present? && check_in_date >= check_out_date
        errors.add(:check_out_date, "must be after the check-in date")
    end
  end
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord

  has_many :recipes

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :room_types, dependent: :destroy
  accepts_nested_attributes_for :room_types, allow_destroy: true
  
  has_many :bookings
  has_many :reviews

  validates :hotel_name, presence: true
  validates :location, presence: true
  validates :contact_details, presence: true

  #has_one_attached :photo_gallery
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :cuisine

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :hotel

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :comment, presence: true
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  belongs_to :hotel
  has_many :bookings

  validates :name, presence: true
  validates :capacity, presence: true
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :bookings, dependent: :destroy

  def name
    "#{first_name} #{last_name}"
  end
  
  def editor? 
    self.role == 'editor' 
  end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/admin/bookings_controller.rb
# app/controllers/admin/bookings_controller.rb
module Admin
  class BookingsController < ApplicationController
    before_action :authenticate_admin
    before_action :set_booking, only: [:show, :destroy, :cancel]

    def show
      # Ensure @booking is set by set_booking before_action
    end

      def confirm
      @booking = Booking.find(params[:id])
      if @booking.update(status: 'confirmed')
        redirect_to admin_booking_path(@booking), notice: 'Booking successfully confirmed.'
      else
        redirect_to admin_booking_path(@booking), alert: 'Failed to confirm booking.'
      end
    end

    def cancel
      # Implement cancellation logic here
      if @booking.cancel
        redirect_to admin_dashboard_path, notice: 'Booking was successfully cancelled.'
      else
        redirect_to admin_dashboard_path, alert: 'Failed to cancel the booking.'
      end
    end

    private

    def set_booking
      @booking = Booking.find(params[:id])
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_hotel, only: [:new, :create]
  
  def index
    @bookings = Booking.all
  end
  
  def new
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    @booking.hotel = @hotel

    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end


  private

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date, :room_type_id, :status)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    @cuisines = Cuisine.all
  end 

  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = @cuisine.recipes
  end 

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @room_types = @hotel.room_types
    @reviews = @hotel.reviews
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end



  private

  def hotel_params
    params.require(:hotel).permit(:hotel_name, :description, :location, :contact_details, :amenities)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :require_editor, only: [:edit]
  before_action :require_admin, only: [:destroy]

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render 'edit'
      end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_url
  end 

  private
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to hotel_path(@review.hotel)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :hotel_id, :rating, :comment, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end 

  def create
    puts params[:email]
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      redirect_to login_url
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        redirect_to signup_url
    end
  end 

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/bookings/show.html.erb
<div class="booking-details">
  <h2>Booking Details</h2>
  <p><strong>Hotel:</strong> <%= @booking.hotel.hotel_name %></p>
  <p><strong>Customer:</strong> <%= @booking.user.name %></p>
  <p><strong>Check-in Date:</strong> <%= @booking.check_in_date %></p>
  <p><strong>Check-out Date:</strong> <%= @booking.check_out_date %></p>
  <p><strong>Status:</strong> <%= @booking.status.try(:capitalize) %></p>

  <% if @booking.status == 'pending' %>
      <%= link_to "Cancel Booking", cancel_admin_booking_path(@booking), method: :delete, data: { confirm: 'Are you sure you want to cancel this booking?' }, class: 'btn btn-danger' %>
    <% end %>

    <%= link_to "Back to Admin Dashboard", admin_dashboard_path, class: "btn btn-secondary" %>


</div>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<table>
  <thead>
    <tr>
      <th>Booking ID</th>
      <th>Hotel</th>
      <th>Room Type</th>
      <th>Check-in Date</th>
      <th>Check-out Date</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.id %></td>
        <td><%= booking.hotel.hotel_name %></td>
        <td><%= booking.room_type.name %></td>
        <td><%= booking.check_in_date %></td>
        <td><%= booking.check_out_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class="booking-new">
  <div class="container">
    <h1>Book a Room at <%= @hotel.hotel_name %></h1>
    <%= form_with(model: @booking, url: hotel_bookings_path(@hotel), local: true) do |f| %>
      <%= f.hidden_field :hotel_id, value: @hotel.id %>
      <div class="field">
        <%= f.label :check_in_date %>
        <%= f.date_field :check_in_date %>
      </div>
      <div class="field">
        <%= f.label :check_out_date %>
        <%= f.date_field :check_out_date %>
      </div>
      <div class="field">
        <%= f.label :room_type_id, "Room Type" %>
        <%= f.collection_select :room_type_id, @hotel.room_types, :id, :name %>
      </div>
      <%= f.submit "Book Now", class: "book-now-btn" %>
    <% end %>
  </div>
  <% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
    <ul>
    <% @booking.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="booking-show">
  <div class="container">
    <h1>Booking Details</h1>
    <p><strong>Hotel:</strong> <%= @booking.hotel.hotel_name %></p>
    <p><strong>Check-in Date:</strong> <%= @booking.check_in_date %></p>
    <p><strong>Check-out Date:</strong> <%= @booking.check_out_date %></p>
    <p><strong>Room Type:</strong> <%= @booking.room_type.name %></p>
   <p><strong>Status:</strong> <%= @booking.status.try(:capitalize) %></p>
    <%= link_to "Back to Hotels", hotels_path, class: "back-btn" %>
  </div>
</div>