config/routes.rb
Rails.application.routes.draw do
  # User Authentication Routes
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Basic Hotel Routes
  resources :hotels do
    resources :reviews, only: [:new, :create]
    resources :room_types, only: [:index, :show]
    resources :bookings, only: [:new, :create, :show]
  end

  # Booking Routes
  resources :bookings, only: [:new, :create, :show, :index]

  # Admin Namespace
  namespace :admin do
    # Admin Dashboard
    get '/', to: 'dashboard#index', as: :dashboard

    # Admin Hotel Management
    resources :hotels, except: [:show] do
      resources :room_types, only: [:new, :create, :edit, :update, :destroy]
    end

    # Admin Booking Management
    resources :bookings, only: [:index, :show, :destroy] do
      member do
        patch 'cancel'
      end
    end

    # Admin User Management
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  # Define root route
  root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hotel
  belongs_to :room_type

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validate :check_dates

  enum status: { pending: 0, confirmed: 1, cancelled: 2 }
  
  private
  def set_default_status
    self.status ||= :pending
  end
  
  def check_dates
      if check_in_date.present? && check_out_date.present? && check_in_date >= check_out_date
        errors.add(:check_out_date, "must be after the check-in date")
    end
  end
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord

  has_many :recipes

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :room_types, dependent: :destroy
  accepts_nested_attributes_for :room_types, allow_destroy: true
  
  has_many :bookings
  has_many :reviews

  validates :hotel_name, presence: true
  validates :location, presence: true
  validates :contact_details, presence: true

  #has_one_attached :photo_gallery
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :cuisine

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :hotel

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :comment, presence: true
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  belongs_to :hotel
  has_many :bookings

  validates :name, presence: true
  validates :capacity, presence: true
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :bookings, dependent: :destroy

  def name
    "#{first_name} #{last_name}"
  end
  
  def editor? 
    self.role == 'editor' 
  end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_action :require_admin

    def index
      @hotels = Hotel.all
      @bookings = Booking.all
      @users = User.all
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @room_types = @hotel.room_types
    @reviews = @hotel.reviews
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end



  private

  def hotel_params
    params.require(:hotel).permit(:hotel_name, :description, :location, :contact_details, :amenities)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :require_editor, only: [:edit]
  before_action :require_admin, only: [:destroy]

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render 'edit'
      end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_url
  end 

  private
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to hotel_path(@review.hotel)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :hotel_id, :rating, :comment, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        redirect_to signup_url
    end
  end 

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<div class="admin-dashboard">
  <div class="container">
    <h1>Admin Dashboard</h1>
    <div class="hotel-listings">
      <h2>Hotel Listings</h2>
      <%= link_to "New Hotel Listing", new_admin_hotel_path, class: "new-btn" %>
      <table>
        <thead>
          <tr>
            <th>Hotel Name</th>
            <th>Location</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @hotels.each do |hotel| %>
            <tr>
              <td><%= hotel.hotel_name %></td>
              <td><%= hotel.location %></td>
              <td>
                <%= link_to "Edit", edit_admin_hotel_path(hotel), class: "edit-btn" %>
               <%= link_to "Delete", admin_hotel_path(hotel), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="bookings-list">
      <h2>Bookings</h2>
      <table>
        <thead>
          <tr>
            <th>Hotel</th>
            <th>Customer</th>
            <th>Check-in Date</th>
            <th>Check-out Date</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.hotel.hotel_name %></td>
              <td><%= booking.user.name %></td>
              <td><%= booking.check_in_date %></td>
              <td><%= booking.check_out_date %></td>
              <td><%= booking.status %></td>
              <td>
                <%= link_to "View", admin_booking_path(booking), class: "view-btn" %>
                <% if booking.status == 'pending' %>
                  <%= link_to "Confirm", confirm_admin_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to confirm this booking?" }, class: "confirm-btn" %>
                <% end %>
                <%= link_to "Cancel", cancel_admin_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to cancel this booking?" }, class: "cancel-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="user-management">
      <h2>Users</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.role %></td>
              <td>
                <%= link_to "Edit", edit_admin_user_path(user), class: "edit-btn" %>
                <%= link_to "Delete", admin_user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>