config/routes.rb
Rails.application.routes.draw do
  # User Authentication Routes
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Basic Hotel Routes
  resources :hotels do
    resources :reviews, only: [:new, :create]
    resources :room_types, only: [:index, :show]
    resources :bookings, only: [:new, :create, :show]
  end

  # Booking Routes
  resources :bookings, only: [:new, :create, :show, :index]

  # Admin Namespace
  namespace :admin do
    # Admin Dashboard
    get '/', to: 'dashboard#index', as: :dashboard

    # Admin Hotel Management
    resources :hotels, except: [:show] do
      resources :room_types, only: [:new, :create, :edit, :update, :destroy]
    end

    # Admin Booking Management
    resources :bookings, only: [:index, :show, :destroy] do
      member do
        patch 'cancel'
      end
    end

    # Admin User Management
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  # Define root route
  root 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hotel
  belongs_to :room_type

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validate :check_dates

  enum status: { pending: 0, confirmed: 1, cancelled: 2 }
  
  private
  def set_default_status
    self.status ||= :pending
  end
  
  def check_dates
      if check_in_date.present? && check_out_date.present? && check_in_date >= check_out_date
        errors.add(:check_out_date, "must be after the check-in date")
    end
  end
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord

  has_many :recipes

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :room_types, dependent: :destroy
  accepts_nested_attributes_for :room_types, allow_destroy: true
  
  has_many :bookings
  has_many :reviews

  validates :hotel_name, presence: true
  validates :location, presence: true
  validates :contact_details, presence: true

  #has_one_attached :photo_gallery
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :cuisine

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :hotel

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :comment, presence: true
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  belongs_to :hotel
  has_many :bookings

  validates :name, presence: true
  validates :capacity, presence: true
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :bookings, dependent: :destroy

  def name
    "#{first_name} #{last_name}"
  end
  
  def editor? 
    self.role == 'editor' 
  end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/admin/hotels_controller.rb
# app/controllers/admin/hotels_controller.rb
module Admin
  class HotelsController < ApplicationController
    before_action :authenticate_admin # Ensure admin authentication
    before_action :set_hotel, only: [:edit, :update, :destroy]

    def index
      @hotels = Hotel.all
    end

    def new
      @hotel = Hotel.new
      @hotel.room_types.build
    end

    def create
      @hotel = Hotel.new(hotel_params)
      if @hotel.save
        redirect_to admin_hotels_path, notice: 'Hotel listing was successfully created.'
      else
        render :new
      end
    end

    def edit
      @hotel = Hotel.find(params[:id])
    end

    def update
      if @hotel.update(hotel_params)
        redirect_to admin_hotels_path, notice: 'Hotel listing was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @hotel = Hotel.find(params[:id])
      if @hotel.destroy
        redirect_to admin_dashboard_path, notice: 'Hotel listing was successfully deleted.'
      else
        redirect_to admin_dashboard_path, alert: 'Failed to delete the hotel listing.'
      end
    end

    private

    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:hotel_name, :description, :location, :contact_details, :amenities)
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_hotel, only: [:new, :create]
  
  def index
    @bookings = Booking.all
  end
  
  def new
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    @booking.hotel = @hotel

    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end


  private

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date, :room_type_id, :status)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    @cuisines = Cuisine.all
  end 

  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = @cuisine.recipes
  end 

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @room_types = @hotel.room_types
    @reviews = @hotel.reviews
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end



  private

  def hotel_params
    params.require(:hotel).permit(:hotel_name, :description, :location, :contact_details, :amenities)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :require_editor, only: [:edit]
  before_action :require_admin, only: [:destroy]

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render 'edit'
      end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_url
  end 

  private
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to hotel_path(@review.hotel)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :hotel_id, :rating, :comment, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end 

  def create
    puts params[:email]
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      redirect_to login_url
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        redirect_to signup_url
    end
  end 

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/hotels/_form.html.erb
<!-- /app/views/admin/hotels/_form.html.erb -->

<%= form_with(model: @hotel, local: true) do |f| %>
  <div class="field">
    <%= f.label :hotel_name %>
    <%= f.text_field :hotel_name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :contact_details %>
    <%= f.text_area :contact_details %>
  </div>
  <div class="field">
    <%= f.label :amenities %>
    <%= f.text_area :amenities %>
  </div>

  <!-- Nested attributes for room types -->
  <%= f.fields_for :room_types do |room_type_fields| %>
    <div class="nested-fields">
      <%= room_type_fields.label :name, "Room Type Name" %>
      <%= room_type_fields.text_field :name %>
      
      <%= room_type_fields.label :description, "Room Type Description" %>
      <%= room_type_fields.text_area :description %>
      
      <%= room_type_fields.label :capacity, "Capacity" %>
      <%= room_type_fields.number_field :capacity %>
      
      <%= room_type_fields.label :price_per_night, "Price per Night" %>
      <%= room_type_fields.number_field :price_per_night, step: 0.01 %>
      
      <%= room_type_fields.check_box :_destroy, class: 'remove-room-type' %>
      <%= room_type_fields.label :_destroy, 'Remove' %>
    </div>
  <% end %>



  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/hotels/edit.html.erb
<!-- /app/views/admin/hotels/edit.html.erb -->
<h1>Edit Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', admin_hotels_path %>

app/views/admin/hotels/new.html.erb
<div class="hotel-form">
  <div class="container">
    <h1>New Hotel</h1>
    <%= render 'form', hotel: @hotel %>
  </div>
</div>

app/views/hotels/index.html.erb
<div class="hotels">
  <div class="container">
    <% @hotels.each do |hotel| %>
      <div class="hotel">
        <h2><%= hotel.hotel_name %></h2>
        <img class="arrow" src="https://content.codecademy.com/courses/rails-auth/img/arrow.svg" width="80" height="40">
        <p><%= link_to "View Hotel", hotel_path(hotel) %></p>
    <% end %>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="hotel-show">
  <div class="container">
    <h1><%= @hotel.hotel_name %></h1>
    <div class="hotel-details">
      <p><strong>Description:</strong> <%= @hotel.description %></p>
      <p><strong>Location:</strong> <%= @hotel.location %></p>
      <p><strong>Contact:</strong> <%= @hotel.contact_details %></p>
      <p><strong>Amenities:</strong> <%= @hotel.amenities %></p>
    </div>
    
    <div class="room-types">
      <h2>Available Room Types</h2>
      <% @hotel.room_types.each do |room_type| %>
        <div class="room-type">
          <h3><%= room_type.name %></h3>
          <p><strong>Description:</strong> <%= room_type.description %></p>
          <p><strong>Capacity:</strong> <%= room_type.capacity %> people</p>
          <p><strong>Price per night:</strong> <%= number_to_currency(room_type.price_per_night) %></p>
        </div>
      <% end %>
    </div>
    
    <div class="reviews">
      <h2>Reviews</h2>
      <% @hotel.reviews.each do |review| %>
        <div class="review">
          <p><strong>Rating:</strong> <%= review.rating %>/5</p>
          <p><strong>Comment:</strong> <%= review.comment %></p>
          <p><strong>Date:</strong> <%= review.date %></p>
        </div>
      <% end %>
    </div>
    
    <% if current_user %>
      <%= link_to "Book Now", new_booking_path(hotel_id: @hotel.id), class: "book-now-btn" %>
    <% end %>
  </div>
</div>